#pragma once

#define TAPPING_TERM 150

#define MASTER_LEFT
#define SOFT_SERIAL_PIN D2

#define SPLIT_OLED_ENABLE
// #define SPLIT_LAYER_STATE_ENABLE
#define OLED_BRIGHTNESS 64
#define OLED_UPDATE_INTERVAL 40

#define USB_POLLING_INTERVAL_MS 1
#define PERMISSIVE_HOLD
#define MAX_DEFERRED_EXECUTORS 7
#define COMBO_TERM 50
#define SMTD_GLOBAL_TAP_TERM 170
#define SMTD_GLOBAL_SEQUENCE_TERM 200

#define SPLIT_TRANSACTION_IDS_USER SYNC_LEDS

// Define a custom transaction ID for LED syncing
#define SYNC_LEDS ID_USER_TOP
